import Head from "next/head";
import { Interested } from "@/components/landing-page";
import Info from "@/components/blog";
import { LayoutFn } from "@/components/Layout";

export default function Blog() {
  return (
    <>
      <Head>
        <title>BPMI | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <LayoutFn>
          <Info />
          <div
            className={`bg-[url(/mem.jpg)] bg-no-repeat bg-cover flex justify-center items-center p-4 md:p-20 z-20 relative mb-20`}
          >
            <Interested />
          </div>
        </LayoutFn>
      </main>
    </>
  );
}
