import Head from "next/head";
import { Hero, Layout, Links, PLink, styles } from "@/components";
import { Interested } from "@/components/landing-page";
import { cards, ourObjs } from "@/constants/about";
import { AiFillLike } from "react-icons/ai";

export default function Home() {
  return (
    <>
      <Head>
        <title>BPMI | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Layout>
          <Hero img={"aboutHero"} title={"About BPMI"}></Hero>
          <section className="">
            <div className="flex justify-center items-center mb-4 md:mb-12">
              <PLink
                styles="text-gray mr-3 text-[17px] cursor-pointer"
                href="/"
                text="Home"
              />
              /
              <h5 className="text-paleBlue border-b ml-3 text-[17px]">
                ABOUT US
              </h5>
            </div>
            <div className="flex flex-col md:flex-row sm:px-10 px-4  sm:pb-20 pb-4">
              <ul className="list-none flex md:flex-col mb-10">
                <Links />
              </ul>
              <div className={`${styles.paddingX}`}>
                <div
                  className={`flex grow justify-around flex-wrap md:mb-20 mb-10 `}
                >
                  {cards.map((card, idx) => (
                    <div
                      key={idx}
                      className="w-[300px] sm:w-[360px] shadow-lg p-3 bg-white border border-darkGray mb-14"
                    >
                      <h3 className="font-bold text-primary text-[25px] mb-3">
                        {card?.title}
                      </h3>
                      {card.content && (
                        <p className=" text-[18px]  lg:text-[25px] text-gray font-normal">
                          {card.content}
                        </p>
                      )}
                      {card.list && (
                        <ul>
                          {card.list.map((item, idx) => (
                            <li
                              key={idx}
                              className=" text-[18px]  lg:text-[25px] text-gray font-normal"
                            >
                              {item}
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                </div>
                <div className="my-3 md:my-10">
                  <h3 className="font-bold text-primary  text-[25px]  lg:text-[36px] mb-5">
                    ABOUT BUSINESS PROCESS MANAGEMENT INSTITUTE
                  </h3>
                  <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                    The Business Process Management Institute is established to
                    develop and promote the practice of business process
                    management in Nigeria. This is based on the desire to ensure
                    that the highest quality valued is provided by the BPM
                    practitioners in Nigeria. This is to be achieved by
                    providing high quality training required to develop
                    intending and already existing practitioners in the field of
                    business process management. Networking platforms and
                    communities are created to ensure that the BPM practitioners
                    meet regularly to exchange ideas and deliberate on the
                    continuous growth of the BPM Practice. Ensuring that
                    employers of practitioners get value from members of the
                    institute.
                  </p>
                </div>
                <div className="">
                  <h3 className="font-bold text-primary   text-[25px]  lg:text-[36px] mb-5">
                    Our Objectives
                  </h3>
                  {ourObjs.map((obj, idx) => (
                    <div key={idx} className="flex w-full mb-3 md:mb-6">
                      <div className="pr-1">
                        <AiFillLike className="text-primary  text-[25px]  lg:text-[36px]" />
                      </div>
                      <p className="font-normal  text-[18px]  lg:text-[25px] text-black">
                        {obj}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </section>
          <div
            className={`bg-[url(/aboutMem.jpg)] bg-no-repeat bg-cover flex justify-center items-center p-4 md:p-20 z-20 relative`}
          >
            <Interested />
          </div>
        </Layout>
      </main>
    </>
  );
}
