import Head from "next/head";
import { Inter } from "@next/font/google";
import { Hero, Layout, styles } from "@/components";
import { Interested } from "@/components/landing-page";
import { links } from "@/constants/landingPage";
import { cards, ourObjs } from "@/constants/about";
import { AiFillLike } from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>BPMI | About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Layout>
          <Hero img={"aboutHero"} title={"About BPMI"}></Hero>
          <section className="">
            <div className="flex justify-center mb-4 md:mb-12">
              <h5 className="text-gray mr-3 text-[17px]">Home</h5>/{" "}
              <h5 className="text-paleBlue border-b ml-3 text-[17px]">
                ABOUT US
              </h5>
            </div>
            <div className="flex flex-col md:flex-row sm:px-10 px-4  sm:pb-20 pb-4">
              <ul className="list-none flex flex-col   ">
                {links.map((link, index) => (
                  <li
                    key={link.id}
                    className={`font-play  cursor-pointer font-bold text-[25px] p-2  text-link border-darkGray whitespace-nowrap 
border-b-2
                `}
                  >
                    <a
                      href={`${link.id}`}
                      className={
                        link.title === "Sign in"
                          ? "pl-6 border-l-[3px]  border-primary"
                          : ""
                      }
                    >
                      {link.title}
                    </a>
                  </li>
                ))}
              </ul>
              <div className={`${styles.paddingX}`}>
                <div className={`flex grow justify-around md:mb-20 mb-10 `}>
                  {cards.map((card, idx) => (
                    <div
                      key={idx}
                      className="w-[300px] sm:w-[360px] shadow-lg p-3 bg-white border border-darkGray"
                    >
                      <h3 className="font-bold text-primary text-[25px] mb-3">
                        {card?.title}
                      </h3>
                      {card.content && (
                        <p className="text-[25px] text-gray font-normal">
                          {card.content}
                        </p>
                      )}
                      {card.list && (
                        <ul>
                          {card.list.map((item, idx) => (
                            <li
                              key={idx}
                              className="text-[25px] text-gray font-normal"
                            >
                              {item}
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                </div>
                <div className="my-3 md:my-10">
                  <h3 className="font-bold text-primary text-[36px] mb-5">
                    ABOUT BUSINESS PROCESS MANAGEMENT INSTITUTE
                  </h3>
                  <p className="font-normal text-[25px] text-black">
                    The Business Process Management Institute is established to
                    develop and promote the practice of business process
                    management in Nigeria. This is based on the desire to ensure
                    that the highest quality valued is provided by the BPM
                    practitioners in Nigeria. This is to be achieved by
                    providing high quality training required to develop
                    intending and already existing practitioners in the field of
                    business process management. Networking platforms and
                    communities are created to ensure that the BPM practitioners
                    meet regularly to exchange ideas and deliberate on the
                    continuous growth of the BPM Practice. Ensuring that
                    employers of practitioners get value from members of the
                    institute.
                  </p>
                </div>
                <div className="">
                  <h3 className="font-bold text-primary  text-[36px] mb-5">
                    Our Objectives
                  </h3>
                  {ourObjs.map((obj, idx) => (
                    <div key={idx} className="flex w-full mb-3 md:mb-6">
                      <div className="pr-1">
                        <AiFillLike className="text-primary text-[36px]" />
                      </div>
                      <p className="font-normal text-[25px] text-black">
                        {obj}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </section>

          <Interested pic={"aboutMem"} />
        </Layout>
      </main>
    </>
  );
}
