import Head from "next/head";
import { Interested } from "@/components/landing-page";

import { LayoutFn } from "@/components/Layout";
import { Hero, PLink, styles } from "@/components";
import Image from "next/image";

export default function Advocacy() {
  return (
    <>
      <Head>
        <title>BPMI | Advocacy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <LayoutFn>
          <Hero img={"reel"} title={"ADVOCACY"}></Hero>
          <div className={`mb-10 md:mb-20 ${styles.paddingX}`}>
            <div className="grid xl:grid-cols-4 lg:grid-cols-3 gap-4 lg:gap-2 sm:grid-cols-2">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((a) => (
                <div className="" key={a}>
                  <Image src={"/advoc.jpg"} alt={""} width={500} height={370} />
                  <div className="p-2">
                    <p className="text-[26px] mb-6 font-play ">June 20, 2022</p>
                    <h3 className="font-bold text-[30px] leading-7 text-primary ">
                      Lorem ipsum dolor sit amet
                    </h3>
                    <p className="font-normal text-[18px] my-4 text-black font-play">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Ac, eget urna ornare etiam nulla at. Mauris tempus
                      pharetra morbi at morbi. rna ornare etiam nulla at. Mauris
                      tempus pharetra morbi at morbi......
                    </p>
                    <PLink
                      href=""
                      styles="bg-primary text-white"
                      text={"Read more"}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div
            className={`bg-[url(/mem.jpg)] bg-no-repeat bg-cover flex justify-center items-center p-4 md:p-20 z-20 relative mb-20`}
          >
            <Interested />
          </div>
        </LayoutFn>
      </main>
    </>
  );
}
