import Head from "next/head";
import { Inter } from "@next/font/google";
import { Layout } from "@/components";
import { About, GetMore, Interested } from "@/components/landing-page";
import { links } from "@/constants/landingPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>BPMI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Layout>
          Hero
          <ul className="list-none flex justify-between  items-center flex-1">
            {links.map((link, index) => (
              <li
                key={link.id}
                className={`font-play  cursor-pointer font-bold text-[25px] p-2  text-link whitespace-nowrap 

                `}
              >
                <a
                  href={`${link.id}`}
                  className={
                    link.title === "Sign in"
                      ? "pl-6 border-l-[3px] border-primary"
                      : ""
                  }
                >
                  {link.title}
                </a>
              </li>
            ))}
          </ul>
          <About />
          <GetMore />
          <Interested pic={"mem"} />
        </Layout>
      </main>
    </>
  );
}
