import Head from "next/head";
import { Hero, Layout } from "@/components";
import { Interestedfn } from "@/components/landing-page";
import Info from "@/components/news";

export default function News() {
  return (
    <>
      <Head>
        <title>BPMI | News</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Layout>
          <Hero img={"shelf"} title={"News"} />
          <Info />
          <Interestedfn />
        </Layout>
      </main>
    </>
  );
}
