import Head from "next/head";
import { useState } from "react";
import { Button, DashboardLayout as Layout } from "@/components";
import { FaImages } from "react-icons/fa";
import { HiOutlineFlag } from "react-icons/hi";

export default function Home() {
  const [file, setFile] = useState("");

  const handleFileChange = (e: string) => {
    const fileName: any = e.split("\\").pop();
    setFile(fileName);
  };

  return (
    <>
      <Head>
        <title>BPMI | Add Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Layout>
          <h2 className="text-4xl mb-4 md:mb-8">Add Posts</h2>
          <div className="grid md:grid-cols-5 md:gap-5 pb-10 md:pb-20">
            <div className="md:col-span-3">
              <div className="bg-[#7B7CB2] p-4 md:p-8 text-white rounded-2xl mb-4 md:mb-8">
                <div className="flex justify-between mb-4 md:mb-8">
                  <h3>Add Images</h3>
                  <div className="">i</div>
                </div>
                <div className="bg-[#6163a3] min-h-[200px] rounded-2xl mb-4 md:mb-10 flex items-center shadow-inner border border-gray">
                  <input
                    type="file"
                    name="file"
                    id="file"
                    onChange={(e) => handleFileChange(e.target.value)}
                    className="w-[0.1px] h-[0.1px] opacity-0 overflow-hidden absolute z-0"
                  />
                  <label htmlFor="file" className="w-full">
                    <div className="flex flex-col justify-center  items-center">
                      <FaImages className="text-8xl" />
                      <p>Drop your images here, or browse</p>
                    </div>
                  </label>
                  {/* <label htmlFor="file">john {file}</label> */}
                </div>
              </div>
              <div className="bg-[#7B7CB2] p-4 md:p-8 text-white rounded-2xl">
                <div className="flex items-center mb-4 md:mb-8">
                  <HiOutlineFlag className="text-lg" />
                  <h3 className="ml-2 md:ml-4">Post Details</h3>
                </div>
                <form className="w-full">
                  <div className="flex flex-wrap -mx-3 mb-6">
                    <div className="w-full  pl-3   pr-20">
                      <label htmlFor="" className="">
                        Title
                      </label>
                      <input
                        className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 my-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                        // id="grid-password"
                        type="text"
                      />
                    </div>
                  </div>
                  <div className="flex flex-wrap -mx-3 mb-6">
                    <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                      <input
                        className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4
                mb-3
                leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                        id="grid-city"
                        type="text"
                        placeholder="City"
                      />
                    </div>
                    <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                      <div className="relative">
                        <select
                          className="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded
                mb-3

                  leading-tight focus:outline-none focus:bg-white focus:border-gray-500 text-gray"
                          id="grid-state"
                        >
                          <option>Lagos</option>
                          <option>Missouri</option>
                          <option>Texas</option>
                        </select>
                        <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                          <svg
                            className="fill-current h-4 w-4"
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20"
                          >
                            <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                          </svg>
                        </div>
                      </div>
                    </div>
                    <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                      <input
                        className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4
                mb-3

                leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                        // id="grid-zip"
                        type="text"
                        placeholder="Country"
                      />
                    </div>
                  </div>
                  <div className="flex flex-wrap -mx-3 mb-6">
                    <div className="w-full  px-3     ">
                      <label htmlFor="" className="pb-20">
                        Details
                      </label>
                      <textarea className="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 my-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 min-h-[300px]" />
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div className="md:col-span-2">
              <h2 className="text-4xl mb-10">Preview</h2>
              <div className="flex mb-6">
                <div className="h-[300px] w-[250px] bg-[#D9D9D9]  mr-4" />
                {"  "}
                <div className="h-[300px] w-[250px] bg-[#D9D9D9] " />
              </div>
              <h3 className="text-[16px] md:text-[22px] font-bold text-primary my-2 ">
                MAN CALLS FOR PATRONAGE OF MADE IN NIGERIA COVID-19 PREVENTIVE
                MATERIALS
              </h3>
              <p className="text-[14px] md:text-[18px] font-normal text-primary py-8">
                The Manufacturers Association of Nigeria has called on Nigerians
                to patronize Made in Nigeria face masks, hand sanitizers, nylon
                hand gloves and other materials as appropriate protective gears
                towards preventing the spread of COVID-19 pandemic.
              </p>
              <p className="text-[14px] md:text-[18px] font-normal text-primary ">
                Acting Director General of the Association, Mr Ambrose Oruche
                stressed that members of the Clothing and Textile, and
                Pharmaceutical sector of MAN have risen to the occasion of
                manufacturing in large quantity particularly effective face mask
                with filters that perform the same function as the imported
                ones.
              </p>
              <p className="text-[14px] md:text-[18px] font-normal text-primary py-8">
                He further stressed the importance of wearing a face mask on a
                regular basis while going about daily activities within the
                restricted period stipulated by government.
              </p>
              <p className="text-[14px] md:text-[18px] font-normal text-primary pb-8">
                For ease of identifying manufacturers of these materials, he
                directed retailers to visit the website of the
                Associationhttp://manufacturersnigeria.org/NewsDetails.aspx?NID=5099
                for the contact of MAN accredited face mask and other safety
                gears manufacturers. Comments (0)
              </p>

              <div className=" flex justify-between pr-10 my-8">
                <Button text="Save" styles="bg-[#E8E8E8] p-4" />
                <Button text="Save & Post" styles="bg-primary p-4 text-white" />
                <Button text="Delete" styles=" bg-[#FF0000] p-4 text-white" />
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
